-- 复杂事件
BIZLOG
----
SELECT *
FROM BIZLOG
MATCH_RECOGNIZE (
PARTITION BY DATAID
ORDER BY OPERATIONTIME
MEASURES
A.OPERATIONTIME AS 新增时间,
B.OPERATIONTIME AS 非修改删除时间,
C.OPERATIONTIME AS 删除时间
ONE ROW PER MATCH
PATTERN (A B C)
DEFINE
A AS OPERATIONNAME = '新增',
B AS NOT OPERATIONNAME = '修改' AND NOT OPERATIONNAME = '删除',
C AS OPERATIONNAME = '删除'
) AS T
----
新增后紧接着未经修改的一步操作便删除了的异常事件（该查询供测试用）
