-- 复杂事件
操作日志流
----
SELECT *
FROM 操作日志流
MATCH_RECOGNIZE (
PARTITION BY DATAID
ORDER BY OPERATIONTIME
MEASURES
A.OPERATIONTIME AS 新增时间,
C.OPERATIONTIME AS 删除时间
ONE ROW PER MATCH
PATTERN (A B* C)
DEFINE
A AS OPERATIONNAME = '新增',
B AS NOT OPERATIONNAME = '修改' AND NOT OPERATIONNAME = '删除',
C AS OPERATIONNAME = '删除'
) AS T
----
新增后未经修改便删除了的异常事件
